-- ==========================================
-- 1. XÓA CỘT topic_count VÀ quiz_count TỪ BẢNG lessons
-- ==========================================
ALTER TABLE public.lessons DROP COLUMN IF EXISTS topic_count;
ALTER TABLE public.lessons DROP COLUMN IF EXISTS quiz_count;

-- ==========================================
-- 2. XÓA TẤT CẢ TOPICS CŨ VÀ THÊM MỚI VỚI VIDEO URLs CHÍNH XÁC
-- ==========================================
DELETE FROM public.topics;

-- LỚP 1 - KỲ 1
INSERT INTO public.topics (id, lesson_id, semester, title, video_url, description, order_index) VALUES
  ('L1-1', 'L1', 1, 'Các số từ 1 đến 10', 'https://www.youtube.com/embed/EX8DR1YMlRE', 'Học đếm số cơ bản.', 1),
  ('L1-2', 'L1', 1, 'Các số 4, 5', 'https://www.youtube.com/embed/tLoZ3HB3n7c', 'Tiếp tục làm quen với các số từ 4, 5', 2),
  ('L1-3', 'L1', 1, 'Các số 6, 7, 8, 9', 'https://www.youtube.com/embed/6mEtEcxAOnQ', 'Khám phá các số từ 6 đến 9', 3),
  ('L1-4', 'L1', 1, 'Số 10 và ôn tập', 'https://www.youtube.com/embed/lRXAnk0wiGI', 'Học số 10 và ôn tập tất cả các số đã học', 4),
  ('L1-5', 'L1', 1, 'Số 0', 'https://www.youtube.com/embed/aMJgvwRAL_k', 'Học Làm quen với số 0', 5),
  ('L1-6', 'L1', 1, 'So Sánh Các Dấu Cho Bé Mới Bắt Đầu', 'https://www.youtube.com/embed/nz5PWLtaokw', 'Cách dùng các dấu trong phép so sánh', 6),
  ('L1-7', 'L1', 1, 'Học Cách So Sánh Nhiều Hơn, Ít Hơn, Bằng Nhau', 'https://www.youtube.com/embed/Z8P-pmHMxDU', 'Học cách nhận biết và so sánh số lượng: nhiều – ít – bằng nhau', 7),
  ('L1-8', 'L1', 1, 'Vẽ Đoạn Thẳng Có Độ Dài Cho Trước Như Thế Nào?', 'https://www.youtube.com/embed/F3yktQ99TYw', 'Học cách kẻ vẽ đoạn thẳng có độ dài chính xác.', 8),
  ('L1-9', 'L1', 1, 'Học Cách Cộng Trong Phạm Vi 4, 5, 6 Đơn Giản', 'https://www.youtube.com/embed/Ei0_VugQejo', 'Làm quen với phép cộng trong phạm vi 4, 5 và 6', 9),
  ('L1-10', 'L1', 1, 'Hiểu Nhanh Số 0 Trong Phép Cộng', 'https://www.youtube.com/embed/9zOo65_BiuQ', 'Tìm hiểu Ý nghĩa của số 0 trong phép cộng', 10),
  ('L1-11', 'L1', 1, 'Học Cách Cộng Trong Phạm Vi 6, 7, 8 Đơn Giản', 'https://www.youtube.com/embed/Qq8r7-feu6s', 'Làm quen với phép cộng trong phạm vi 6, 7 và 8', 11),
  ('L1-12', 'L1', 1, 'Học Cách Cộng Trong Phạm Vi 9, 10 Đơn Giản', 'https://www.youtube.com/embed/s-goxNdmJPE', 'Làm quen với phép cộng trong phạm vi 9 và 10', 12),
  ('L1-13', 'L1', 1, 'Học Cách Cộng Các Số Tròn Chục', 'https://www.youtube.com/embed/yd5JHf4Blh0', 'Biết cách cộng các số tròn chục.', 13),
  ('L1-14', 'L1', 1, 'Học Cách Trừ Trong Phạm Vi 3, 4, 5 Đơn Giản', 'https://www.youtube.com/embed/55l906_zUyE', 'Làm quen với phép trừ trong phạm vi 3, 4 và 5', 14),
  ('L1-15', 'L1', 1, 'Hiểu Nhanh Số 0 Trong Phép Trừ', 'https://www.youtube.com/embed/CyeG3y7lKeg', 'Tìm hiểu Ý nghĩa của số 0 trong phép trừ', 15),
  ('L1-16', 'L1', 1, 'Phân Biệt Điểm Ở Trong Hay Ở Ngoài Một Hình', 'https://www.youtube.com/embed/-Cnwmbv69Aw', 'Nhận biết điểm nằm trong hoặc ngoài một hình phẳng', 16),
  ('L1-17', 'L1', 1, 'Nhận Biết Vị Trí: Trên – Dưới, Trái – Phải, Trước – Sau, Ở Giữa', 'https://www.youtube.com/embed/ZD5O7uPbWhw', 'Nhận biết các vị trí cơ bản.', 17),
  ('L1-18', 'L1', 1, 'Học Cách So Sánh Nhiều Hơn, Ít Hơn, Bằng Nhau (Ôn tập)', 'https://www.youtube.com/embed/Z8P-pmHMxDU', 'Học cách nhận biết và so sánh số lượng: nhiều – ít – bằng nhau.', 18),
  ('L1-19', 'L1', 1, 'Nhận Biết Vị Trí (Ôn tập)', 'https://www.youtube.com/embed/ZD5O7uPbWhw', 'Nhận biết các vị trí cơ bản.', 19),
  -- LỚP 1 - KỲ 2
  ('L1-20', 'L1', 2, 'Làm Quen Với Đồng Hồ Và Thời Gian', 'https://www.youtube.com/embed/mIPRUr0rrOc', 'Làm quen và nhận biết đồng hồ và thời gian.', 20),
  ('L1-21', 'L1', 2, 'Xăng-ti-mét (cm)', 'https://www.youtube.com/embed/RJFSVVGgiTw', 'Làm quen với đơn vị đo độ dài Xăng-ti-mét (cm)', 21),
  ('L1-22', 'L1', 2, 'Nhận Biết Các Hình Học Cơ Bản: Vuông, Tròn, Tam Giác, Chữ Nhật', 'https://www.youtube.com/embed/W3UzjLDA6M4', 'Nhận biết các hình học cơ bản', 22),
  ('L1-23', 'L1', 2, 'Khối Lập Phương – Khối Hộp Chữ Nhật Là Gì?', 'https://www.youtube.com/embed/udOvVRBYfxo', 'Nhận biết hình khối cơ bản.', 23),
  ('L1-24', 'L1', 2, 'Học Cách Đo Độ Dài Chính Xác', 'https://www.youtube.com/embed/_Z6BNEvcZHI', 'Hiểu khái niệm đo độ dài là gì.', 24),
  ('L1-25', 'L1', 2, 'Làm Quen Với Các Số Từ 11 Đến 16 Dễ Hiểu', 'https://www.youtube.com/embed/xj6xmgfPTYA', 'Làm quen với các số từ 11 đến 16', 25),
  ('L1-26', 'L1', 2, 'Làm Quen Với Các Số Từ 17 Đến 20 Dễ Hiểu', 'https://www.youtube.com/embed/cj_H-yURTkk', 'Làm quen với các số từ 17 đến 20.', 26),
  ('L1-27', 'L1', 2, 'Làm Quen Với Các Số Từ 21 Đến 40', 'https://www.youtube.com/embed/kbd23ca3BTs', 'Làm quen với các số từ 21 đến 40.', 27),
  ('L1-28', 'L1', 2, 'Làm Quen Với Các Số Từ 71 Đến 99', 'https://www.youtube.com/embed/vRSD68RnrHg', 'Làm quen với các số từ 71 đến 99.', 28),
  ('L1-29', 'L1', 2, 'Phép Trừ Dạng 27 - 4 Và 63 - 40 Dễ Hiểu Dễ Nhớ', 'https://www.youtube.com/embed/_VJBjfIPXUw', 'Làm quen với phép trừ dạng 27 - 4 và 63 - 40', 29),
  ('L1-30', 'L1', 2, 'Học Cách So Sánh Độ Dài: Dài Hơn Hay Ngắn Hơn?', 'https://www.youtube.com/embed/dl-mzVa01N0', 'Quan sát và so sánh độ dài', 30),
  ('L1-31', 'L1', 2, 'Làm Quen Với Các Số Từ 41 Đến 70', 'https://www.youtube.com/embed/WOcDMWIiBFY', 'Làm quen với các số từ 41 đến 70', 31),
  
  -- LỚP 2 - KỲ 1
  ('L2-1', 'L2', 1, 'Nhận Biết Đơn Vị Chục, Trăm, Nghìn', 'https://www.youtube.com/embed/GqOC3khhHYk', 'Nhận Biết Đơn Vị Chục, Trăm, Nghìn', 1),
  ('L2-2', 'L2', 1, 'Học So Sánh Các Số Tròn Trăm', 'https://www.youtube.com/embed/w_9hbyNwbEw', 'Học So Sánh Các Số Tròn Trăm', 2),
  ('L2-3', 'L2', 1, 'Làm Quen Với Các Số Từ 111 Đến 200', 'https://www.youtube.com/embed/lrc8idC9Itc', 'Làm Quen Với Các Số Từ 111 Đến 200', 3),
  ('L2-4', 'L2', 1, 'Làm Quen Với Các Số Có Ba Chữ Số', 'https://www.youtube.com/embed/tklyRfsxrq8', 'Làm Quen Với Các Số Có Ba Chữ Số', 4),
  ('L2-5', 'L2', 1, 'Học Cách Tìm Một Số Hạng Trong Một Tổng', 'https://www.youtube.com/embed/iq4s2yWVFYE', 'Học Cách Tìm Một Số Hạng Trong Một Tổng', 5),
  ('L2-6', 'L2', 1, 'Phân Biệt Ngày, Giờ, Xem Đồng Hồ', 'https://www.youtube.com/embed/HPsUJQ4amsM', 'Phân Biệt Ngày, Giờ, Xem Đồng Hồ', 6),
  ('L2-7', 'L2', 1, 'Phân Biệt Ngày, Tháng, Xem Lịch', 'https://www.youtube.com/embed/FfM5bGSUsJ4', 'Phân Biệt Ngày, Tháng, Xem Lịch', 7),
  ('L2-8', 'L2', 1, 'Ki-Lo-Gam (Kg) Là Gì?', 'https://www.youtube.com/embed/P5TGyT263tg', 'Ki-Lo-Gam (Kg) Là Gì?', 8),
  ('L2-9', 'L2', 1, 'Lít (L) Là Gì?', 'https://www.youtube.com/embed/sq6w6YTOy2g', 'Lít (L) Là Gì?', 9),
  ('L2-10', 'L2', 1, 'Nhận Biết Tiền Việt Nam', 'https://www.youtube.com/embed/ysFv_hBPiM8', 'Nhận Biết Tiền Việt Nam', 10),
  ('L2-11', 'L2', 1, 'Học Cách Giải Bài Toán Về Nhiều Hơn', 'https://www.youtube.com/embed/CTBmx61GEU8', 'Học Cách Giải Bài Toán Về Nhiều Hơn', 11),
  ('L2-12', 'L2', 1, 'Học Cách Giải Các Bài Toán Về Tuổi', 'https://www.youtube.com/embed/Xem-B2yn_f0', 'Học Cách Giải Các Bài Toán Về Tuổi', 12),
  ('L2-13', 'L2', 1, 'Làm Quen Với Số Hạng – Tổng Trong Phép Cộng', 'https://www.youtube.com/embed/5Szi-0_PRC8', 'Làm Quen Với Số Hạng – Tổng Trong Phép Cộng', 13),
  ('L2-14', 'L2', 1, 'Làm Quen Với Số Bị Trừ – Số Trừ – Hiệu', 'https://www.youtube.com/embed/3WVHjJfKivs', 'Làm Quen Với Số Bị Trừ – Số Trừ – Hiệu', 14),
  -- LỚP 2 - KỲ 2
  ('L2-15', 'L2', 2, 'Khi Số Có Tận Cùng Là 1 Trừ Đi Một Số', 'https://www.youtube.com/embed/7oMjY5lXYRo', 'Khi Số Có Tận Cùng Là 1 Trừ Đi Một Số', 15),
  ('L2-16', 'L2', 2, 'Khi Số Có Tận Cùng Là 2 Trừ Đi Một Số', 'https://www.youtube.com/embed/G2S8vsjxFnw', 'Khi Số Có Tận Cùng Là 2 Trừ Đi Một Số', 16),
  ('L2-17', 'L2', 2, 'Làm Quen Với Kết Hợp Phép Tính', 'https://www.youtube.com/embed/YtBWfbUzGO4', 'Làm Quen Với Kết Hợp Phép Tính', 17),
  ('L2-18', 'L2', 2, 'Phép Cộng, Trừ Không Nhớ Trong Phạm Vi 1000', 'https://www.youtube.com/embed/VV_8RWXr5P0', 'Phép Cộng, Trừ Không Nhớ Trong Phạm Vi 1000', 18),
  ('L2-19', 'L2', 2, 'Làm Quen Với Thừa Số - Tích Trong Phép Nhân', 'https://www.youtube.com/embed/TcdHD4aAXZM', 'Làm Quen Với Thừa Số - Tích Trong Phép Nhân', 19),
  ('L2-20', 'L2', 2, 'Làm Quen Với Số Bị Chia - Số Chia - Thương', 'https://www.youtube.com/embed/aKKma5Pbe_o', 'Làm Quen Với Số Bị Chia - Số Chia - Thương', 20),
  ('L2-21', 'L2', 2, 'Khi Số 1 Trong Phép Nhân Và Phép Chia', 'https://www.youtube.com/embed/bMu4KVezAy8', 'Khi Số 1 Trong Phép Nhân Và Phép Chia', 21),
  ('L2-22', 'L2', 2, 'Làm Quen Với Đường Gấp Khúc - Độ Dài Đường Gấp Khúc', 'https://www.youtube.com/embed/stX8wTTHbhg', 'Làm Quen Với Đường Gấp Khúc - Độ Dài Đường Gấp Khúc', 22),
  ('L2-23', 'L2', 2, 'Học So Sánh Các Số Có Ba Chữ Số', 'https://www.youtube.com/embed/LmpZNBdynyM', 'Học So Sánh Các Số Có Ba Chữ Số', 23),
  ('L2-24', 'L2', 2, 'Khi Phép Cộng Có Tổng Bằng 100', 'https://www.youtube.com/embed/QpltsNVai3U', 'Khi Phép Cộng Có Tổng Bằng 100', 24),
  ('L2-25', 'L2', 2, 'Học Cách Tìm Một Thừa Số Của Phép Nhân', 'https://www.youtube.com/embed/Ky0QKfWGLIk', 'Học Cách Tìm Một Thừa Số Của Phép Nhân', 25),
  ('L2-26', 'L2', 2, 'Học Nhanh Bảng Chia 4 - Một Phần Tư', 'https://www.youtube.com/embed/F9h_I64L1qM', 'Học Nhanh Bảng Chia 4 - Một Phần Tư', 26),
  
  -- LỚP 3 - KỲ 1
  ('L3-1', 'L3', 1, 'Số có 4 chữ số', 'https://www.youtube.com/embed/Ydqfpq0iisw?si=BzhPS_5QAANaEvmh', 'Làm quen với số có 4 chữ số', 1),
  ('L3-2', 'L3', 1, 'Hệ thống số la mã', 'https://www.youtube.com/embed/QW_SF3hO7rU?si=W5Xq1DSATJ-qpR5c', 'Làm Quen Với Hệ Thống Số La Mã', 2),
  ('L3-3', 'L3', 1, 'Số có 5 chữ số', 'https://www.youtube.com/embed/GOVlVSwXot0?si=yGjfxU5rk_pyQ2hX', 'Làm Quen Với Số Có 5 Chữ Số', 3),
  ('L3-4', 'L3', 1, 'Xem đồng hồ', 'https://www.youtube.com/embed/46qb_FhcsRE?si=PeKBqtmco8mJfaIT', 'Học cách xem đồng hồ', 4),
  ('L3-5', 'L3', 1, 'Đồng hồ và số la mã', 'https://www.youtube.com/embed/6VnQ8wXMyy0?si=1VAKSSYneNt7zMqi', 'Học về đồng hồ và số la mã', 5),
  ('L3-6', 'L3', 1, 'Tháng - năm', 'https://www.youtube.com/embed/7PfYgTsy3vk', 'Học Về Tháng - Năm', 6),
  ('L3-7', 'L3', 1, 'Bảng đơn vị đo độ dài', 'https://www.youtube.com/embed/aKcRhDuiJns', 'Làm Quen Với Bảng Đơn Vị Đo Độ Dài', 7),
  ('L3-8', 'L3', 1, 'GAM(G)', 'https://www.youtube.com/embed/DX0zXC5TKnA', 'Gam (G) Là Gì', 8),
  ('L3-9', 'L3', 1, 'Bài Toán Về Độ Dài', 'https://www.youtube.com/embed/PmhBGSO1VvU', 'Bài Toán Về Độ Dài', 9),
  ('L3-10', 'L3', 1, 'Xăng-ti-mét Vuông (Cm²)', 'https://www.youtube.com/embed/_X0BSP8TBA4', 'Xăng-ti-mét Vuông (Cm²) Là Gì?', 10),
  ('L3-11', 'L3', 1, 'Tiền Việt Nam', 'https://www.youtube.com/embed/oUzl55VNQM0', 'Học về tiền Việt Nam', 11),
  ('L3-12', 'L3', 1, 'Thống Kê Số Liệu', 'https://www.youtube.com/embed/evdksCTk-Ag', 'Làm Quen Với Thống Kê Số Liệu', 12),
  ('L3-13', 'L3', 1, 'Nhân - Chia 6 ( Phần 1 )', 'https://www.youtube.com/embed/ydQxUjdtZDM', 'Học Nhanh Bảng Nhân - Chia 6', 13),
  ('L3-14', 'L3', 1, 'Nhân - Chia 6 ( Phần 2 )', 'https://www.youtube.com/embed/0-0_NyDc2kM', 'Học Nhanh Bảng Nhân - Chia 6', 14),
  ('L3-15', 'L3', 1, 'Nhân - Chia 7', 'https://www.youtube.com/embed/0-0_NyDc2kM', 'Học Nhanh Bảng Nhân - Chia 7', 15),
  ('L3-16', 'L3', 1, 'Nhân - Chia 8', 'https://www.youtube.com/embed/GJ-tlux3DEk', 'Học Nhanh Bảng Nhân - Chia 8', 16),
  ('L3-17', 'L3', 1, 'Nhân Số Có 2 Chữ Số Với Số Có 1 Chữ Số', 'https://www.youtube.com/embed/GJ-tlux3DEk', 'Học Nhân Số Có 2 Chữ Số Với Số Có 1 Chữ Số', 17),
  ('L3-18', 'L3', 1, 'Nhân Số Có 3 Chữ Số Với Số Có 1 Chữ Số', 'https://www.youtube.com/embed/uP9PEhu99Q4', 'Học Nhân Số Có 3 Chữ Số Với Số Có 1 Chữ Số', 18),
  ('L3-19', 'L3', 1, 'Chia Số Có 2 Chữ Số Cho Số Có 1 Chữ Số', 'https://www.youtube.com/embed/0-0_NyDc2kM', 'Học Chia Số Có 2 Chữ Số Cho Số Có 1 Chữ Số', 19),
  ('L3-20', 'L3', 1, 'Dãy số', 'https://www.youtube.com/embed/FCCfoClQ1CA', 'Học Nhanh Về Dãy Số', 20),
  -- LỚP 3 - KỲ 2
  ('L3-21', 'L3', 2, 'Các Phép Toán Được Định Nghĩa Qua Ký Hiệu', 'https://www.youtube.com/embed/XQZl7jqJ6Xk', 'Làm Quen Với Các Phép Toán Được Định Nghĩa Qua Ký Hiệu', 21),
  ('L3-22', 'L3', 2, 'Tìm Một Trong Các Phần Bằng Nhau Của Một Số', 'https://www.youtube.com/embed/wFj0e1tqIlQ', 'Học Tìm Một Trong Các Phần Bằng Nhau Của Một Số', 22),
  ('L3-23', 'L3', 2, 'Gấp Một Số Lên Nhiều Lần', 'https://www.youtube.com/embed/Bft1I3R0nlg', 'Học Về Gấp Một Số Lên Nhiều Lần', 23),
  ('L3-24', 'L3', 2, 'Giảm Đi Một Số Lần', 'https://www.youtube.com/embed/IW2l8gYADMA', 'Học Về Giảm Đi Một Số Lần', 24),
  ('L3-25', 'L3', 2, 'So Sánh Số Lớn Gấp Mấy Lần Số Bé', 'https://www.youtube.com/embed/u0i2sZXEjqo', 'Học Cách So Sánh Số Lớn Gấp Mấy Lần Số Bé', 25),
  ('L3-26', 'L3', 2, 'So Sánh Số Bé Bằng Một Phần Mấy Số Lớn', 'https://www.youtube.com/embed/poaRzIUZhhI', 'Học Cách So Sánh Số Bé Bằng Một Phần Mấy Số Lớn', 26),
  ('L3-27', 'L3', 2, 'Các Bài Toán Đếm Hình, Cắt Ghép Hình', 'https://www.youtube.com/embed/9WNEJgPUAxU', 'Học Về Các Bài Toán Đếm Hình, Cắt Ghép Hình', 27),
  ('L3-28', 'L3', 2, 'Điểm Ở Giữa, Trung Điểm Của Đoạn Thẳng', 'https://www.youtube.com/embed/LKtfGiPykH8', 'Học Về Điểm Ở Giữa, Trung Điểm Của Đoạn Thẳng', 28),
  ('L3-29', 'L3', 2, 'Hình Chữ Nhật Và Các Yếu Tố Trong Hình Chữ Nhật', 'https://www.youtube.com/embed/X-YE7UZFdSU', 'Nhận Biết Hình Chữ Nhật Và Các Yếu Tố Trong Hình Chữ Nhật', 29),
  ('L3-30', 'L3', 2, 'Chu Vi - Diện Tích Hình Chữ Nhật', 'https://www.youtube.com/embed/PFeQZZIAqv8', 'Làm Quen Với Chu Vi - Diện Tích Hình Chữ Nhật', 30),
  ('L3-31', 'L3', 2, 'Chu Vi - Diện Tích Hình Vuông', 'https://www.youtube.com/embed/zoewMBqRJ30', 'Làm Quen Với Chu Vi - Diện Tích Hình Vuông', 31),
  ('L3-32', 'L3', 2, 'Hình Tròn Và Các Yếu Tố Của Hình Tròn', 'https://www.youtube.com/embed/huPEJRlzmBo', 'Nhận Biết Hình Tròn Và Các Yếu Tố Của Hình Tròn', 32),
  ('L3-33', 'L3', 2, 'Biểu Thức', 'https://www.youtube.com/embed/EQqx6fj_dtE', 'Học Tính Giá Trị Biểu Thức', 33),
  ('L3-34', 'L3', 2, 'Chia Số Có 3 Chữ Số Cho Số Có 1 Chữ Số', 'https://www.youtube.com/embed/wWX5fFWMco4', 'Học Chia Số Có 3 Chữ Số Cho Số Có 1 Chữ Số', 34),
  ('L3-35', 'L3', 2, 'Phép Chia Hết và Phép Chia Có Dư', 'https://www.youtube.com/embed/wFj0e1tqIlQ', 'Học Về Phép Chia Hết và Phép Chia Có Dư', 35),
  ('L3-36', 'L3', 2, 'Phép Cộng - Trừ Các Số Trong Phạm Vi 10.000', 'https://www.youtube.com/embed/wFj0e1tqIlQ', 'Làm Quen Với Phép Cộng - Trừ Các Số Trong Phạm Vi 10.000', 36),
  ('L3-37', 'L3', 2, 'Nhân Số Có 4 Chữ Số Với Số Có 1 Chữ Số', 'https://www.youtube.com/embed/wFj0e1tqIlQ', 'Học Nhân Số Có 4 Chữ Số Với Số Có 1 Chữ Số', 37),
  ('L3-38', 'L3', 2, 'Chia số Có 4 Chữ Số Cho Số Có 1 Chữ Số', 'https://www.youtube.com/embed/wFj0e1tqIlQ', 'Học Chia số Có 4 Chữ Số Cho Số Có 1 Chữ Số', 38),
  ('L3-39', 'L3', 2, 'Phép Cộng - Trừ Các Số Trong Phạm Vi 100.000', 'https://www.youtube.com/embed/wFj0e1tqIlQ', 'Làm Quen Với Phép Cộng - Trừ Các Số Trong Phạm Vi 100.000', 39),
  ('L3-40', 'L3', 2, 'Nhân Số Có 5 Chữ Số Với Số Có 1 Chữ Số', 'https://www.youtube.com/embed/wFj0e1tqIlQ', 'Học Nhân Số Có 5 Chữ Số Với Số Có 1 Chữ Số', 40),
  ('L3-41', 'L3', 2, 'Chia Số Có 5 Chữ Số Cho Số Có 1 Chữ Số', 'https://www.youtube.com/embed/wFj0e1tqIlQ', 'Học Chia Số Có 5 Chữ Số Cho Số Có 1 Chữ Số', 41),
  ('L3-42', 'L3', 2, 'Hình Vuông Và Các Yếu Tố Trong Hình Vuông', 'https://www.youtube.com/embed/o6hTF1CreRc', 'Nhận Biết Hình Vuông Và Các Yếu Tố Trong Hình Vuông', 42),
  
  -- LỚP 4 - KỲ 1
  ('L4-1', 'L4', 1, 'Làm Quen Với Hàng Và Lớp', 'https://www.youtube.com/embed/_78OsABM5Go', 'Học về hàng và lớp trong số học', 1),
  ('L4-2', 'L4', 1, 'Làm Quen Với Số Có 6 Chữ Số', 'https://www.youtube.com/embed/PUfDL4SoktU', 'Học về số có 6 chữ số', 2),
  ('L4-3', 'L4', 1, 'Học Cách So Sánh Số Có Nhiều Chữ Số', 'https://www.youtube.com/embed/GQpqTlbb7eA', 'So sánh các số có nhiều chữ số', 3),
  ('L4-4', 'L4', 1, 'Bài Toán Cấu Tạo Số', 'https://www.youtube.com/embed/YKuRlIbi1NQ', 'Học cách cấu tạo số', 4),
  ('L4-5', 'L4', 1, 'Làm Quen Với Dãy Số Tự Nhiên', 'https://www.youtube.com/embed/_-TfMVI-D-U', 'Tìm hiểu về dãy số tự nhiên', 5),
  ('L4-6', 'L4', 1, 'Viết Số Tự Nhiên Trong Hệ Thập Phân', 'https://www.youtube.com/embed/jl_XHD1bvos', 'Cách viết số tự nhiên trong hệ thập phân', 6),
  ('L4-7', 'L4', 1, 'So Sánh Và Sắp Xếp Thứ Tự Số Tự Nhiên', 'https://www.youtube.com/embed/VsnZikILD0g', 'So sánh và sắp xếp số tự nhiên', 7),
  ('L4-8', 'L4', 1, 'Yến - Tạ - Tấn Là Gì?', 'https://www.youtube.com/embed/MDy1SHxpWJQ', 'Đơn vị đo khối lượng: Yến, Tạ, Tấn', 8),
  ('L4-9', 'L4', 1, 'Học Về Giây - Phút - Giờ', 'https://www.youtube.com/embed/BV1pYCm487A', 'Đơn vị đo thời gian', 9),
  ('L4-10', 'L4', 1, 'Học Về Năm - Thế Kỷ', 'https://www.youtube.com/embed/EihlDgamd9g', 'Đơn vị đo thời gian lớn', 10),
  ('L4-11', 'L4', 1, 'Ki-Lô-Mét Vuông (Km²) Là Gì?', 'https://www.youtube.com/embed/CqSa1zDsI3A', 'Đơn vị đo diện tích', 11),
  ('L4-12', 'L4', 1, 'Tìm Số Trung Bình Cộng', 'https://www.youtube.com/embed/S-1zGc1PJIg', 'Học cách tính trung bình cộng', 12),
  ('L4-13', 'L4', 1, 'Toán nâng cao về trung bình cộng', 'https://www.youtube.com/embed/tpbs7BfMooc', 'Các bài toán nâng cao về trung bình cộng và ứng dụng', 13),
  ('L4-14', 'L4', 1, 'Phân tích biểu đồ dạng bảng', 'https://www.youtube.com/embed/djLFzp3ni9U', 'Học cách đọc và phân tích dữ liệu từ biểu đồ dạng bảng', 14),
  ('L4-15', 'L4', 1, 'Phân tích biểu đồ cột', 'https://www.youtube.com/embed/TumAMV9lvX8', 'Học cách đọc và phân tích dữ liệu từ biểu đồ dạng cột', 15),
  ('L4-16', 'L4', 1, 'Tìm quy luật của dãy số cho trước', 'https://www.youtube.com/embed/I7RIVgXcEpI', 'Phương pháp nhận biết và tìm quy luật của các dãy số', 16),
  ('L4-17', 'L4', 1, 'Tìm số số hạng, tổng của dãy số có quy luật', 'https://www.youtube.com/embed/0wB3Ucw7YWg', 'Cách tính số các số hạng và tổng của dãy số theo quy luật', 17),
  ('L4-18', 'L4', 1, 'Liên hệ giữa các thành phần phép cộng trừ', 'https://www.youtube.com/embed/XH_AKXsFqiE', 'Mối quan hệ giữa số hạng, tổng, số bị trừ, số trừ và hiệu', 18),
  ('L4-19', 'L4', 1, 'Biểu thức có chứa 3 chữ', 'https://www.youtube.com/embed/GABdQGL3kL0', 'Tìm hiểu và giải các biểu thức chứa ba chữ số', 19),
  ('L4-20', 'L4', 1, 'Tính chất kết hợp của phép cộng trừ', 'https://www.youtube.com/embed/W5pFnY6JFhE', 'Học và vận dụng tính chất kết hợp trong phép cộng và trừ', 20),
  ('L4-21', 'L4', 1, 'Tìm 2 số khi biết tổng hiệu', 'https://www.youtube.com/embed/J6xVfNcCVWw', 'Phương pháp giải bài toán tìm hai số khi biết tổng và hiệu', 21),
  ('L4-22', 'L4', 1, 'Bài toán tổng hiệu trong hình học', 'https://www.youtube.com/embed/8MDAB6mNVfs', 'Áp dụng phương pháp tổng hiệu vào bài toán hình học', 22),
  ('L4-23', 'L4', 1, 'Nhân với số có 1 chữ số', 'https://www.youtube.com/embed/Rc4KRx31ktU', 'Phương pháp nhân một số nhiều chữ số với số có 1 chữ số', 23),
  ('L4-24', 'L4', 1, 'Nhân với số tận cùng là 0', 'https://www.youtube.com/embed/cNd1HNY53wY', 'Kỹ thuật nhân nhanh với các số có tận cùng là chữ số 0', 24),
  ('L4-25', 'L4', 1, 'Nhân nhẩm số có 2 chữ số với 11', 'https://www.youtube.com/embed/wzmUD3yo4PY', 'Mẹo nhân nhẩm nhanh số có 2 chữ số với số 11', 25),
  ('L4-26', 'L4', 1, 'Nhân với số có 3 chữ số', 'https://www.youtube.com/embed/PakvL2dwLJo', 'Phương pháp nhân một số với số có 3 chữ số', 26),
  ('L4-27', 'L4', 1, 'Tính chất kết hợp của phép nhân', 'https://www.youtube.com/embed/O6vMOWxH7Z0', 'Học và vận dụng tính chất kết hợp trong phép nhân', 27),
  ('L4-28', 'L4', 1, 'Phân Số - Khái Niệm Cơ Bản', 'https://www.youtube.com/embed/qR55ASMG5nY', 'Làm quen với khái niệm phân số cơ bản', 28),
  ('L4-29', 'L4', 1, 'So Sánh Hai Phân Số', 'https://www.youtube.com/embed/LzUD77f91O0', 'Học cách so sánh hai phân số', 29),
  ('L4-30', 'L4', 1, 'Rút Gọn Phân Số', 'https://www.youtube.com/embed/ykYH7hLpnKs', 'Phương pháp rút gọn phân số', 30),
  ('L4-31', 'L4', 1, 'Quy Đồng Mẫu Số Các Phân Số', 'https://www.youtube.com/embed/c5PFUOlbs7Y', 'Học cách quy đồng mẫu số', 31),
  ('L4-32', 'L4', 1, 'Cộng Hai Phân Số Cùng Mẫu', 'https://www.youtube.com/embed/qTVeLSorjOM', 'Thực hành cộng phân số cùng mẫu', 32),
  ('L4-33', 'L4', 1, 'Cộng Hai Phân Số Khác Mẫu', 'https://www.youtube.com/embed/dMUKlOBCDR0', 'Cách cộng phân số khác mẫu số', 33),
  ('L4-34', 'L4', 1, 'Trừ Hai Phân Số Cùng Mẫu', 'https://www.youtube.com/embed/NvuqWO3nCuY', 'Phép trừ phân số cùng mẫu', 34),
  -- LỚP 4 - KỲ 2
  ('L4-35', 'L4', 2, 'Trừ Hai Phân Số Khác Mẫu', 'https://www.youtube.com/embed/1b3WCwKTyMU', 'Cách trừ phân số khác mẫu số', 35),
  ('L4-36', 'L4', 2, 'Bài Toán Có Lời Văn Về Phân Số', 'https://www.youtube.com/embed/wGTztQfLa_s', 'Giải các bài toán có lời văn liên quan đến phân số', 36),
  ('L4-37', 'L4', 2, 'Nhân Phân Số Với Số Tự Nhiên', 'https://www.youtube.com/embed/vDPNHCxgVFA', 'Học phép nhân phân số với số tự nhiên', 37),
  ('L4-38', 'L4', 2, 'Chia Phân Số Cho Số Tự Nhiên', 'https://www.youtube.com/embed/zqi6pTvTaEw', 'Cách chia phân số cho số tự nhiên', 38),
  ('L4-39', 'L4', 2, 'Hỗn Số - Khái Niệm Và Ứng Dụng', 'https://www.youtube.com/embed/YVzo8wMO4XU', 'Tìm hiểu về hỗn số và cách sử dụng', 39),
  ('L4-40', 'L4', 2, 'Chuyển Đổi Giữa Hỗn Số Và Phân Số', 'https://www.youtube.com/embed/cwv-AJQSsrw', 'Cách chuyển đổi hỗn số thành phân số và ngược lại', 40),
  ('L4-41', 'L4', 2, 'Tính Chất Cơ Bản Của Phân Số', 'https://www.youtube.com/embed/084j1ojliuo', 'Các tính chất quan trọng của phân số', 41),
  ('L4-42', 'L4', 2, 'Số Thập Phân - Làm Quen', 'https://www.youtube.com/embed/gzBulq_6lNI', 'Giới thiệu về số thập phân', 42),
  ('L4-43', 'L4', 2, 'Đọc Và Viết Số Thập Phân', 'https://www.youtube.com/embed/WBG5O0Nf_zs', 'Cách đọc và viết số thập phân chính xác', 43),
  ('L4-44', 'L4', 2, 'So Sánh Số Thập Phân', 'https://www.youtube.com/embed/4jlZ5IVc-Uk', 'Học cách so sánh các số thập phân', 44),
  ('L4-45', 'L4', 2, 'Cộng Số Thập Phân', 'https://www.youtube.com/embed/mONOQSJ5-AM', 'Phép cộng các số thập phân', 45),
  ('L4-46', 'L4', 2, 'Trừ Số Thập Phân', 'https://www.youtube.com/embed/z2iPadFG57A', 'Phép trừ các số thập phân', 46),
  ('L4-47', 'L4', 2, 'Nhân Số Thập Phân Với 10, 100, 1000', 'https://www.youtube.com/embed/22B9LDJNRdo', 'Quy tắc nhân số thập phân với 10, 100, 1000', 47),
  ('L4-48', 'L4', 2, 'Chia Số Thập Phân Cho 10, 100, 1000', 'https://www.youtube.com/embed/uip1WcAXujU', 'Quy tắc chia số thập phân cho 10, 100, 1000', 48),
  ('L4-49', 'L4', 2, 'Diện Tích Hình Chữ Nhật', 'https://www.youtube.com/embed/5-Sr3Wz67nA', 'Công thức tính diện tích hình chữ nhật', 49),
  ('L4-50', 'L4', 2, 'Diện Tích Hình Vuông', 'https://www.youtube.com/embed/FNHdR9NHjhw', 'Công thức tính diện tích hình vuông', 50),
  ('L4-51', 'L4', 2, 'Chu Vi Hình Chữ Nhật', 'https://www.youtube.com/embed/ZXMVxjsm3oI', 'Cách tính chu vi hình chữ nhật', 51),
  ('L4-52', 'L4', 2, 'Chu Vi Hình Vuông', 'https://www.youtube.com/embed/6TIhc5SAyCI', 'Cách tính chu vi hình vuông', 52),
  ('L4-53', 'L4', 2, 'Bài Toán Về Diện Tích Và Chu Vi', 'https://www.youtube.com/embed/1FFCdrqvWR8', 'Giải các bài toán về diện tích và chu vi', 53),
  ('L4-54', 'L4', 2, 'Đo Độ Dài - Đơn Vị Mét', 'https://www.youtube.com/embed/uaROXbAggxM', 'Đơn vị đo độ dài: mét và các đơn vị liên quan', 54),
  ('L4-55', 'L4', 2, 'Đổi Đơn Vị Độ Dài', 'https://www.youtube.com/embed/Jcm_jIVHhOI', 'Cách đổi giữa các đơn vị đo độ dài', 55),
  ('L4-56', 'L4', 2, 'Đo Khối Lượng - Kg, Tạ, Tấn', 'https://www.youtube.com/embed/6eS23g2M7zQ', 'Các đơn vị đo khối lượng và cách đổi', 56),
  ('L4-57', 'L4', 2, 'Đổi Đơn Vị Khối Lượng', 'https://www.youtube.com/embed/6JLOxkAE0T8', 'Chuyển đổi giữa các đơn vị khối lượng', 57),
  ('L4-58', 'L4', 2, 'Thời Gian - Giờ, Phút, Giây', 'https://www.youtube.com/embed/e4dD87bW32g', 'Đơn vị thời gian và cách tính toán', 58),
  ('L4-59', 'L4', 2, 'Tính Khoảng Thời Gian', 'https://www.youtube.com/embed/YLS6AuD8HyQ', 'Cách tính khoảng thời gian giữa hai mốc', 59),
  ('L4-60', 'L4', 2, 'Bài Toán Về Thời Gian', 'https://www.youtube.com/embed/hrKYsWH53yg', 'Giải các bài toán liên quan đến thời gian', 60),
  ('L4-61', 'L4', 2, 'Hình Tam Giác - Nhận Biết', 'https://www.youtube.com/embed/-5QFgd13deU', 'Nhận biết và phân loại hình tam giác', 61),
  ('L4-62', 'L4', 2, 'Các Loại Hình Tam Giác', 'https://www.youtube.com/embed/PDxWFjLCxHU', 'Tam giác vuông, cân, đều và các tính chất', 62),
  ('L4-63', 'L4', 2, 'Hình Thang - Khái Niệm', 'https://www.youtube.com/embed/4vjLPqaosGc', 'Tìm hiểu về hình thang và đặc điểm', 63),
  ('L4-64', 'L4', 2, 'Hình Bình Hành', 'https://www.youtube.com/embed/_mVgyJgs2Zk', 'Hình bình hành và tính chất của nó', 64),
  ('L4-65', 'L4', 2, 'Bài Toán Tổng Hợp Hình Học', 'https://www.youtube.com/embed/ReaBghYw9p4', 'Giải các bài toán hình học tổng hợp', 65),
  ('L4-66', 'L4', 2, 'Ôn Tập Và Củng Cố Kiến Thức', 'https://www.youtube.com/embed/zVEDV1R5lWo', 'Ôn tập toàn bộ kiến thức đã học', 66),
  ('L4-67', 'L4', 2, 'Bài Tập Tổng Hợp Cuối Năm', 'https://www.youtube.com/embed/NKkjX1Z5R38', 'Bài tập tổng hợp ôn thi cuối năm học', 67),
  
  -- LỚP 5 - KỲ 1
  ('L5-1', 'L5', 1, 'Chia Một Số Tự Nhiên Cho Một Số Thập Phân', 'https://www.youtube.com/embed/8Akzlx2xODc', 'Chia Một Số Tự Nhiên Cho Một Số Thập Phân', 1),
  ('L5-2', 'L5', 1, 'Khái Niệm Hỗn Số', 'https://www.youtube.com/embed/PFP0F64bxfI', 'Khái Niệm Hỗn Số', 2),
  ('L5-3', 'L5', 1, 'Chuyển Đổi Hỗn Số Thành Phân Số', 'https://www.youtube.com/embed/M5aZBfU4A7Y', 'Chuyển Đổi Hỗn Số Thành Phân Số', 3),
  ('L5-4', 'L5', 1, 'Đọc, Viết Số Thập Phân', 'https://www.youtube.com/embed/jKuVl8lSUSE', 'Đọc, Viết Số Thập Phân', 4),
  ('L5-5', 'L5', 1, 'So Sánh 2 Số Thập Phân', 'https://www.youtube.com/embed/NSUiNNCdTDE', 'So Sánh 2 Số Thập Phân', 5),
  ('L5-6', 'L5', 1, 'Viết Số Đo Độ Dài Dưới Dạng Số Thập Phân', 'https://www.youtube.com/embed/AjyO6GMldDY', 'Viết Số Đo Độ Dài Dưới Dạng Số Thập Phân', 6),
  ('L5-7', 'L5', 1, 'Ôn tập phép nhân', 'https://www.youtube.com/embed/S19Lbyt8U_0', 'Ôn tập và củng cố kiến thức về phép nhân', 7),
  ('L5-8', 'L5', 1, 'Nhân Một Số Thập Phân Với Một Số Thập Phân', 'https://www.youtube.com/embed/KhsxxdEo2QQ', 'Nhân Một Số Thập Phân Với Một Số Thập Phân', 8),
  ('L5-9', 'L5', 1, 'Chia Một Số Thập Phân Với Một Số Thập Phân', 'https://www.youtube.com/embed/aO0X57Mm91Q', 'Chia Một Số Thập Phân Với Một Số Thập Phân', 9),
  ('L5-10', 'L5', 1, 'Làm Quen Với Tỉ Số Phần Trăm', 'https://www.youtube.com/embed/_Cjo_FpPnqQ', 'Làm Quen Với Tỉ Số Phần Trăm', 10),
  ('L5-11', 'L5', 1, 'Cách Tính Diện Tích Hình Tam Giác', 'https://www.youtube.com/embed/clTUm_OZQb8', 'Cách Tính Diện Tích Hình Tam Giác', 11),
  ('L5-12', 'L5', 1, 'Cách Tính Diện Tích Hình Thang', 'https://www.youtube.com/embed/HMjoeADksbU', 'Cách Tính Diện Tích Hình Thang', 12),
  ('L5-13', 'L5', 1, 'Cách Tính Diện Tích Hình Tròn', 'https://www.youtube.com/embed/TzzJ9PTVoyA', 'Cách Tính Diện Tích Hình Tròn', 13),
  ('L5-14', 'L5', 1, 'Cách Tính Thời Gian, Quãng Đường, Vận Tốc', 'https://www.youtube.com/embed/zFjbAYD3w3w', 'Cách Tính Thời Gian, Quãng Đường, Vận Tốc', 14),
  ('L5-22', 'L5', 1, 'Tìm Tỉ Số Phần Trăm Của 2 Số', 'https://www.youtube.com/embed/kCmwalu89GM', 'Tìm Tỉ Số Phần Trăm Của 2 Số', 15),
  -- LỚP 5 - KỲ 2
  ('L5-15', 'L5', 2, 'Diện Tích Xung Quanh Và Diện Tích Toàn Phần Hình Hộp Chữ Nhật', 'https://www.youtube.com/embed/0YrZsFToDIk', 'Diện Tích Xung Quanh Và Diện Tích Toàn Phần Hình Hộp Chữ Nhật', 16),
  ('L5-16', 'L5', 2, 'Diện Tích Xung Quanh Và Diện Tích Toàn Phần Của Hình Lập Phương', 'https://www.youtube.com/embed/TNgBCGNgl4Q', 'Diện Tích Xung Quanh Và Diện Tích Toàn Phần Của Hình Lập Phương', 17),
  ('L5-23', 'L5', 2, 'Giới Thiệu Về Hình Trụ, Hình Cầu', 'https://www.youtube.com/embed/0NewzRWSTfc', 'Giới Thiệu Về Hình Trụ, Hình Cầu', 18),
  ('L5-24', 'L5', 2, 'Cộng Số Đo Thời Gian', 'https://www.youtube.com/embed/6iRL5OsVLbc', 'Cộng Số Đo Thời Gian', 19),
  ('L5-25', 'L5', 2, 'Trừ Số Đo Thời Gian', 'https://www.youtube.com/embed/v3l00mOpelQ', 'Trừ Số Đo Thời Gian', 20),
  ('L5-26', 'L5', 2, 'Nhân Số Đo Thời Gian', 'https://www.youtube.com/embed/Fl1n_3_Lh40', 'Nhân Số Đo Thời Gian', 21),
  ('L5-27', 'L5', 2, 'Chia Số Đo Thời Gian', 'https://www.youtube.com/embed/c8-5gshbYiI', 'Chia Số Đo Thời Gian', 22),
  ('L5-17', 'L5', 2, 'Thể Tích Của Một Hình', 'https://www.youtube.com/embed/rlGdd3rj3A4', 'Thể Tích Của Một Hình', 23),
  ('L5-18', 'L5', 2, 'Thể Tích Hình Hộp Chữ Nhật', 'https://www.youtube.com/embed/D7AO_NwtoIs', 'Thể Tích Hình Hộp Chữ Nhật', 24),
  ('L5-19', 'L5', 2, 'Thể Tích Hình Lập Phương', 'https://www.youtube.com/embed/99tkJuwuMNQ', 'Thể Tích Hình Lập Phương', 25),
  ('L5-20', 'L5', 2, 'Tìm Số Khi Biết Giá Trị Phần Trăm', 'https://www.youtube.com/embed/vqY27sQnDcM', 'Tìm Số Khi Biết Giá Trị Phần Trăm', 26),
  ('L5-21', 'L5', 2, 'Cách Tìm Giá Trị Của 1 Số', 'https://www.youtube.com/embed/coQV2_IKiac', 'Cách Tìm Giá Trị Của 1 Số', 27);